<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Exam;
use App\Models\ExamQuestion;
use App\Models\Module;
use Illuminate\Database\Seeder;

class ExamSeeder extends Seeder
{
    public function run(): void
    {
        // $examData[courseTitle][moduleOrderIndex] = ['exam_title', 'time_limit_secs', 'questions']
        $examData = [
            // ── COURSE 4: Discipleship ─────────────────────────────────────────
            'Discipleship' => [
                1 => [
                    'exam_title'      => "Understanding the Father's Love in Christ — Module Assessment",
                    'time_limit_secs' => 720,
                    'questions'       => [
                        ['type'=>'mcq','question_text'=>"According to this lesson, where is the full revelation of the Father's love found?",'options'=>['In creation and nature','In Jesus Christ','In the Old Testament Law','In answered prayer'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"This lesson says God's love was not a reaction to man's failure. When did God purpose redemption in Christ?",'options'=>['After Adam sinned','At the time of Noah','Before the foundation of the world','At Christ\'s birth'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>"According to this lesson, the problem Adam's sin caused was deeper than wrong actions — it was a spiritual condition.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'Romans 5:8 says God demonstrated His love in that:','options'=>['He created the world for our pleasure','While we were yet sinners, Christ died for us','He answers all our prayers','He blesses us with good things'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"According to this lesson, how should the question 'How do you know God loves you?' be answered?",'options'=>['From your material blessings and open doors','From your feelings of peace','From the gospel, not from circumstances','From the testimony of other believers'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>"This lesson teaches that God's love IS primarily proven by material possessions, open doors, and breakthroughs.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"1 John 4:9 says God's love was manifested toward us because:",'options'=>['He forgave all our sins','He sent His only begotten Son into the world','He gave us the Holy Scriptures','He blessed us with every good thing'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to this lesson, through Christ Jesus, God brought us into:','options'=>['Servanthood and religious duty','Forgiveness only','Sonship — we are sons and heirs through faith','A covenant of blessings and curses'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>"The 'breadth' of God's love, according to this lesson, refers to:",'options'=>["The eternal security of salvation","How deeply Christ identified with our condition","God's plan in Christ being for all men regardless of race or background","Christ's ascension and present ministry"],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>"This lesson teaches that the gospel is restricted to people of certain tribes, races, or social classes.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"The 'length' of God's love speaks of:",'options'=>["The global reach of the gospel","The eternal security and permanence of what God has done in Christ","How low Christ descended in death","Christ's present intercession"],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'Hebrews 9:12 states that Christ obtained for us:','options'=>['Temporary forgiveness subject to renewal','Conditional redemption based on obedience','Eternal redemption by His own blood','A promise of earthly prosperity'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>"According to this lesson, the believer's eternal life is dependent on human performance and good deeds.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'Romans 8:38-39 teaches that:','options'=>['Serious sins can separate us from God\'s love','Nothing can separate the believer from the love of God in Christ','God\'s love depends on our faithfulness','Only death can separate us from God'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"The 'depth' of God's love is revealed in:",'options'=>["The breadth of the gospel's global reach","How far Christ went in identifying with man's condition through death and resurrection","The eternal security of the believer's salvation","Christ's present intercession at the Father's right hand"],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Romans 4:25, Christ was raised again for our:','options'=>['Healing','Sanctification','Justification','Glorification'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'This lesson teaches that by identification with Christ, the believer is dead to sin and alive unto God (Romans 6:6).','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'Hebrews 2:14 says that through death, Christ rendered ineffective:','options'=>['The Law of Moses','The power of sin','The devil who had the power of death','The traditions of men'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>"The 'height' of God's love is revealed in:",'options'=>["The breadth of the gospel's reach to all men","Christ's death and burial on our behalf","Christ's resurrection, ascension, and present ministry at the Father's right hand","God's mercy shown to sinners"],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'Hebrews 7:25 says Christ is able to save to the uttermost because:','options'=>['He performed many miracles','He ever lives to make intercession for us','He fulfilled the entire Law','He was sinless from birth'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'2 Corinthians 5:21 says we are made:','options'=>['Servants of righteousness','Workers of the Law','The righteousness of God in Christ','Holy through our own efforts'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to Colossians 1:22 as cited in this lesson, Christ presents the believer holy, unblameable, and unreproveable in His sight.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"This lesson says the believer's acceptance before God is based on:",'options'=>['Their prayer life and faithfulness','Human performance and religious duties','Christ\'s finished work','The number of good deeds done'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'According to Romans 5:5, the love of God is shed abroad in our hearts by:','options'=>['Reading Scripture daily','The Holy Ghost given to us','Prayer and fasting','The preaching of the gospel'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"This lesson teaches that Ephesians 3:14-19 speaks of four dimensions of God's love: breadth, length, depth, and height.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to this lesson, what does Philemon 1:6 mean when it says faith becomes effectual?','options'=>['Faith grows through trials and testing','Faith is effective through precise knowledge of what is already true in Christ','Faith is activated by financial giving','Faith increases through church attendance'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"This lesson teaches that our identity in Christ is primarily as:",'options'=>['Forgiven servants who must earn God\'s favour','Sons and heirs through faith in Christ','Workers in God\'s vineyard','Grateful recipients of mercy only'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'This lesson says holiness is first who the believer is in Christ before it is expressed in conduct.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to 1 Corinthians 1:30, God has made Christ unto us wisdom, righteousness, sanctification, and:','options'=>['Peace','Redemption','Power','Healing'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"This lesson's central argument is that God's love is not measured by circumstances but is fully revealed in:",'options'=>['The beauty of creation','The blessings of answered prayer','Christ Himself and His finished work','The growth of the Church'],'correct_answer'=>2],
                    ],
                ],
                2 => [
                    'exam_title'      => 'The Reality of Our Redemption in Christ — Module Assessment',
                    'time_limit_secs' => 720,
                    'questions'       => [
                        ['type'=>'mcq','question_text'=>'According to this lesson, what is the gospel founded on?','options'=>['Feelings and religious experience','Verifiable facts: Christ died, was buried, and rose again','Dreams and visions','Personal performance and moral reform'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'This lesson teaches that the gospel is primarily about what man must do for God.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"According to the lesson, when we say 'Jesus died for us,' what are we declaring?",'options'=>['That Jesus was a martyr for a cause','Substitution — what should have happened to the sinner happened to Jesus','That Jesus set a moral example','That God was punishing Jesus'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'What does the burial of Christ signify according to this lesson?','options'=>['That death was temporary','The completeness and finality of the sacrifice — sin was dealt with in Christ','That Christ needed to rest','A symbolic act with no doctrinal meaning'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Romans 4:25, Christ was raised again for our:','options'=>['Healing','Sanctification','Justification','Glorification'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'This lesson teaches that redemption is complete in the cross alone, even without the resurrection.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"According to this lesson, what did the death of Adam in Genesis 2:17 primarily mean?",'options'=>['Physical death — Adam fell down dead','Non-existence','Separation from the life of God, spiritual alienation, and condemnation','Sickness and disease entered the world'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>"When Jesus cried 'My God, my God, why hast thou forsaken me?' (Matthew 27:46), this lesson says He was:",'options'=>['Acting in fear and confusion','Expressing doubt about His mission','Fulfilling Scripture and identifying with man\'s condition under sin as our Substitute','Calling on God for rescue'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'According to 2 Corinthians 5:21 as explained in this lesson, the Great Exchange means:','options'=>['Jesus sinned so we could be forgiven','Jesus, who knew no sin, was made sin for us so we could be made the righteousness of God in Him','We become righteous by imitating Jesus','Jesus took our punishment but we must still earn righteousness'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'This lesson teaches that righteousness is a reward for improved behaviour and religious activity.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to this lesson, holiness and good works are:','options'=>['The price for acceptance before God','How we earn God\'s love','The fruit of the new life we have received in Christ','Requirements we must meet before God accepts us'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'According to Ephesians 1:7 and Colossians 1:14, forgiveness for the believer is:','options'=>['A future possibility they must work toward','A present possession in Christ','Conditional on continued obedience','Renewed daily through confession'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"What does this lesson say about the 'handwriting that was against us' (Colossians 2:13-15)?",'options'=>['It was reduced and made manageable','It was negotiated and reduced','It was cancelled and nailed to the cross in Christ','It remains until the final judgment'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to this lesson, we reconcile ourselves to God through good behaviour and religious effort.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Romans 8:1, the believer in Christ Jesus:','options'=>['Is under partial condemnation until they mature','Is under no condemnation','Must work to avoid condemnation','May face condemnation if they sin'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Hebrews 2:14-15, through death Christ destroyed:','options'=>['The power of the law','Him that had the power of death — the devil — and delivered those in bondage through fear of death','The power of sickness','The authority of government'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 2 Corinthians 5:17, the believer in Christ is:','options'=>['A forgiven sinner still bound by the old life','A new creation — old things passed away','An improved version of the old man','A work in progress with no present standing'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this lesson, the believer receives not only forgiveness but a new standing, new identity, and new life in Christ.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to this lesson, what is the right response to the gospel?','options'=>['Self-effort and moral reform','Religious performance and church attendance','Faith — to believe the report of Christ\'s death, burial, and resurrection and receive what God has done','Emotional experience and personal visions'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'According to Romans 10:9-10 as cited in this lesson, believing the gospel involves:','options'=>['A lengthy period of moral preparation','Confessing Jesus as Lord and believing God raised Him from the dead','Completing a series of religious rituals','Earning God\'s acceptance through service'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to this lesson, after believing the gospel, growth happens through:','options'=>['Self-discipline and willpower alone','The knowledge of Christ, renewing of the mind, fellowship with believers, and acknowledgement of what is already in us in Christ','Achieving moral perfection','Performing religious duties faithfully'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'This lesson teaches that the Bible is Christocentric — Scripture finds its fulfilment and explanation in Christ.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"According to this lesson, God's purpose from the beginning was to:",'options'=>['Create servants to fulfil His commands','Have sons in Christ who would share His life, nature, and fellowship','Build a religious institution','Establish a moral code for society'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Romans 5:1, the believer has peace with God through:','options'=>['Their own obedience','Prayer and fasting','Our Lord Jesus Christ','The keeping of the law'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'This lesson teaches that Jesus became a sinner by conduct on the cross.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to this lesson, the Law revealed sin and exposed:','options'=>["The path to righteousness through self-effort","Man's inability to achieve righteousness by self-effort — no flesh justified by law-keeping","The way to earn God's favour","That man could achieve redemption through moral discipline"],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'Isaiah 53:3-6 and 1 Peter 2:24 both point to Christ as:','options'=>['A prophet who taught moral values','The Lamb of God who bore our sins','A political revolutionary','A religious reformer'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to this lesson, the resurrection is God's public declaration that Christ's sacrifice was accepted and justification is accomplished.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'Colossians 2:10 says the believer in Christ is:','options'=>['Still striving to become complete','Complete in Him','Partially complete pending obedience','Complete only after a life of holiness'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to this lesson, the gospel message of reconciliation should shape how we treat unbelievers by:','options'=>['Condemning them for their sins','Avoiding them so we are not influenced','Announcing what God has done in Christ so they may receive life — we are ambassadors of reconciliation','Waiting for them to come to us'],'correct_answer'=>2],
                    ],
                ],
                3 => [
                    'exam_title'      => 'The Reality of Our Righteousness in Christ — Module Assessment',
                    'time_limit_secs' => 720,
                    'questions'       => [
                        ['type'=>'mcq','question_text'=>'According to Romans 1:17, where is the righteousness of God revealed?','options'=>['In the Law of Moses','In the lives of holy people','In the gospel','In the Ten Commandments'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'What is the primary meaning of the Greek word dikaiosyne (righteousness) as taught in this module?','options'=>['Moral perfection achieved by effort','The quality and state of being right — right in standing, nature, and relationship with God','A religious title given to church leaders','A feeling of peace during worship'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, righteousness is first what you do, rather than who you are in Christ.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to 2 Corinthians 5:21, who was made sin so that believers could become the righteousness of God?','options'=>['The Holy Spirit','The Apostle Paul','God the Father','Christ — He who knew no sin'],'correct_answer'=>3],
                        ['type'=>'mcq','question_text'=>'According to Romans 3:20, by the deeds of the law no flesh will be:','options'=>['Condemned','Justified in God\'s sight','Blessed','Sanctified'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"This module teaches that righteousness by faith is based entirely on Christ's finished work, not on personal merit.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"In Philippians 3:9, Paul contrasts 'my own righteousness from the law' with:",'options'=>['Righteousness earned by prayer and fasting','Righteousness through faith in Christ — the righteousness from God by faith','Righteousness given to church members after years of service','Righteousness earned through personal sacrifice'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Romans 8:1, what is the present reality for every believer who is in Christ Jesus?','options'=>['They must still earn their standing before God','There is a process of becoming less condemned over time','There is therefore now no condemnation','They remain under partial condemnation until they mature'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>"According to this module, the Law's primary purpose was to produce righteousness in those who kept it.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"According to Romans 5:19, by one Man's obedience, many will be:",'options'=>['Forgiven but not made righteous','Made righteous','Given a second chance at the law','Considered partially righteous'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Romans 4:5, righteousness is credited to:','options'=>['The one who works hard for God','The one who keeps the law perfectly','The one who does not work but believes on Him who justifies the ungodly','The one who earns God\'s favour through sacrifice'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to this module, the fruit of righteousness is what makes the believer righteous before God.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to 1 Corinthians 1:30, Christ is made to the believer: wisdom, __, sanctification, and redemption.','options'=>['Righteousness','Popularity','Earthly prosperity','Freedom from all suffering'],'correct_answer'=>0],
                        ['type'=>'mcq','question_text'=>'Hebrews 10:19-22 teaches that believers can enter the Holiest with:','options'=>['Trembling fear and great unworthiness','Careful religious preparation and penitential rituals','Boldness — by the blood of Jesus','Much moral improvement first'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to this module, righteousness-consciousness gives boldness in prayer and freedom from guilt and condemnation.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"Isaiah 54:14 declares: 'In righteousness you shall be':",'options'=>['Condemned','Established','Tested','Refined'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Romans 10:4, Christ is the __ of the law for righteousness to everyone who believes.','options'=>['Beginning','Fulfilment','End','Continuation'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'This module teaches that knowing your righteousness in Christ is licence to continue sinning freely.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to James 5:16, the effective and fervent prayer of a __ avails much.','options'=>['Righteous man','Religious man','Wise man','Humble man'],'correct_answer'=>0],
                        ['type'=>'mcq','question_text'=>'Ephesians 4:24 describes the new man as created according to God in:','options'=>['Power and glory alone','True righteousness and holiness','Signs and wonders','Perfect knowledge of the law'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Romans 5:1, being justified by faith produces peace with God through our Lord Jesus Christ.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"The 'great exchange' at Calvary means:",'options'=>['Christ adopted our lifestyle and we adopted His','Christ took our sin and gave us His righteousness','We became sinless in daily conduct from the moment we believed','God overlooked sin without any substitutionary act'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Galatians 3:10, those who rely on the works of the law for righteousness are under:','options'=>['Blessing','God\'s grace','A curse','Spiritual maturity'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to this module, a believer established in righteousness loses their standing before God every time they fail.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to 1 John 3:9, the reason a born-again believer does not practise sin as a lifestyle is:','options'=>['Their willpower and moral discipline','God\'s seed remains in them — they have the nature of righteousness','They are kept under strict law-keeping','They have achieved sinless perfection in conduct'],'correct_answer'=>1],
                    ],
                ],
                4 => [
                    'exam_title'      => 'The Reality of the New Creation in Christ — Module Assessment',
                    'time_limit_secs' => 720,
                    'questions'       => [
                        ['type'=>'mcq','question_text'=>'According to 2 Corinthians 5:17, what happens to old things when a person is in Christ?','options'=>['They are gradually improved','They have passed away','They remain as a reminder of the past','They are still there but covered'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, the new creation is an improvement and renovation of the old Adamic nature.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Colossians 2:10, the believer in Christ is:','options'=>['Still becoming complete','Complete in Him','Partially complete','Complete only after years of service'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 1 Corinthians 6:17, someone who is joined to the Lord is:','options'=>['Under obligation to keep the law','One spirit with Him','A servant of God only','A student of His teaching'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"The phrase 'in Christ' occurs only a few times in Paul's letters, indicating it is a minor concept.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Galatians 2:20, who now lives in the believer?','options'=>['The law','The old man','Christ','The apostles'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'According to Ephesians 2:6, where has God seated the believer in Christ?','options'=>['On earth, waiting for heaven','In the heavenly places in Christ Jesus','In a place of trial and testing','In the congregation of the righteous'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Romans 6:14, sin shall have dominion over believers because they are still under the law.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Romans 12:2, the believer is transformed by:','options'=>['Performing religious duties faithfully','The renewing of the mind','Achieving moral perfection','Avoiding all contact with the world'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 2 Peter 1:4, what have believers become partakers of?','options'=>['The divine law','The divine nature','The divine plan for Israel','The divine anger against sin'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to 1 Corinthians 2:16, believers have the mind of Christ.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Colossians 1:27, what is described as the hope of glory?','options'=>['The resurrection','Christ in you','The law fulfilled','The coming kingdom'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 1 Peter 2:9, believers are described as:','options'=>['Sinners saved by grace only','A chosen generation, a royal priesthood, a holy nation','Servants of the law','Slaves set free'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to Galatians 5:1, the new creation is called to stand fast in the liberty Christ has given them.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Romans 8:21, the freedom of the new creation is described as:','options'=>['Freedom to sin without consequences','The glorious freedom of the children of God','Freedom from all earthly responsibility','Freedom from the need to pray'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 2 Corinthians 10:5, the believer is to bring every thought into captivity to:','options'=>['The law of Moses','The obedience of Christ','The elders of the church','Personal convictions'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to John 5:24, the believer in Christ has already passed from death to life.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Ephesians 4:24, the new man is created according to God in:','options'=>['Power and signs','True righteousness and holiness','Knowledge of law and prophecy','Suffering and endurance'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Hebrews 2:14-15, Christ became flesh and blood to destroy the one who had the power of death and to release those held in:','options'=>['Ignorance','Slavery through fear of death','The power of the law','Bondage to ritual'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, the five new creation dimensions are future attainments to be earned through faithful service.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Romans 8:2, what has set the believer free from the law of sin and death?','options'=>['Self-discipline and willpower','The law of the Spirit of life in Christ Jesus','Rigorous fasting and prayer','Keeping the Ten Commandments'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Colossians 3:2, the believer is instructed to set their mind on:','options'=>['Things on the earth','Things above, not on things on the earth','Their personal goals and ambitions','Their ministry achievements'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, the renewed mind is the mechanism through which new creation realities become practical.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to 1 John 3:2, what has not yet been revealed about what the believer will ultimately be?','options'=>['Their heavenly reward','What we shall be — though we know we shall be like Him','Their place in the kingdom','Their spiritual gifts'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Philippians 4:8, what should the new creation mind dwell on?','options'=>['Worldly ambitions and earthly pleasures','Things that are true, noble, just, pure, and praiseworthy','The failures of the past','Political and social problems'],'correct_answer'=>1],
                    ],
                ],
                5 => [
                    'exam_title'      => 'The Reality of Our Fellowship with the Father in Christ — Module Assessment',
                    'time_limit_secs' => 720,
                    'questions'       => [
                        ['type'=>'mcq','question_text'=>'According to 1 Corinthians 1:9, into what has God called every believer?','options'=>['The fellowship of the apostles','The fellowship of His Son, Jesus Christ our Lord','The fellowship of the local church','The fellowship of the law'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"The Greek word koinonia used for 'fellowship' in the New Testament primarily means:",'options'=>['Attending church regularly','Sharing, participation, communion, and joint partnership','A formal religious gathering','A spiritual discipline practised alone'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, fellowship with the Father is reserved as a reward for spiritually mature or advanced believers.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Ephesians 2:18, how do believers have access to the Father?','options'=>['Through the law and commandments','Through church membership','Through Him (Christ) by one Spirit to the Father','Through personal moral achievement'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>"According to Ephesians 3:12, the believer's access to the Father through Christ is described as bold and with confidence.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"According to Hebrews 4:16, believers are invited to come to the throne of grace:",'options'=>['With trembling and great preparation','Boldly, to obtain mercy and find grace','Once a year through a priest','Only after achieving holiness'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"According to John 14:20, what is the structure of the believer's union and fellowship with the Father?",'options'=>['The Father is distant; we seek Him from afar','I am in My Father, and you in Me, and I in you','We are near the Father only in prayer','We fellowship with the Father only through the church'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to 1 Corinthians 6:17, the believer who is joined to the Lord is one spirit with Him.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to 1 John 1:7, walking in the light means the blood of Jesus cleanses us from:','options'=>['Only small sins','All sin','Only sins we are aware of','Sins we have confessed verbally to a priest'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 1 John 1:9, what must the believer do when fellowship is broken by sin?','options'=>['Perform penance for weeks','Simply confess their sins to God','Attend church more regularly','Fast for several days'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, fellowship with the Father is terminated permanently whenever a believer sins.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Romans 8:15, the Spirit of adoption enables the believer to cry out:','options'=>["'I am unworthy'","'Abba, Father'","'Lord, have mercy'","'I believe'"],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"The Aramaic word 'Abba' used in Romans 8:15 most closely means:",'options'=>['Lord God Almighty',"Father — with the intimacy of 'Daddy'",'Holy Creator','Master and Ruler'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to John 15:3, the Word of God plays a role in cleansing the believer.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"According to John 14:23, what is the result when a believer keeps Christ's word?",'options'=>['They receive material blessings','The Father and Son come and make their home with them','They are given leadership in the church','They receive immunity from temptation'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Psalm 25:14, who is given the secret (intimate counsel) of the Lord?','options'=>['Only prophets and priests','Those who fear Him','Only apostles','Those who perform many religious duties'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, prayer at its deepest level is not a religious exercise but the expression of fellowship with the Father.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to John 10:27, which of the following is a characteristic of sheep who know the Shepherd?','options'=>['They never struggle','They hear His voice','They always have material prosperity','They never face trials'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 1 John 1:3, what was the apostolic message designed to bring about in its hearers?','options'=>['Church membership','Fellowship with the Father and with His Son Jesus Christ','Obedience to the law','Personal holiness through effort'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Jeremiah 31:34, the New Covenant promise is that all its members — from least to greatest — shall know God.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Philippians 4:6, what is to be made known to God?','options'=>['Only urgent requests','Requests only after much prayer','Everything — through prayer and supplication with thanksgiving','Only requests for others'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>"According to Ephesians 2:13, how have those who were 'far off' been brought near to God?",'options'=>['Through religious discipline and fasting','By the blood of Christ','Through keeping the law','Through the ministry of the apostles'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to John 17:21-23, the goal of Christ's atonement was to include believers in the fellowship of the Father and the Son.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Romans 8:16, the Spirit Himself bears witness with our spirit that we are:','options'=>['Servants of God','Children of God','Heirs of the law','Under the law'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"According to this module, which of the following best describes the 'two common errors' about fellowship with God?",'options'=>['Pride and laziness','Distance (seeing God as remote and rule-bound) and formalism (reducing fellowship to religious routine)','Legalism and liberalism','Doubt and disobedience'],'correct_answer'=>1],
                    ],
                ],
                6 => [
                    'exam_title'      => 'The Reality of the Indwelling of the Holy Spirit — Module Assessment',
                    'time_limit_secs' => 720,
                    'questions'       => [
                        ['type'=>'mcq','question_text'=>'According to Ezekiel 36:26-27, what did God promise to put within His people under the New Covenant?','options'=>['A new set of laws','His Spirit within them, causing them to walk in His statutes','A new temple in Jerusalem','A new religious system'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Romans 8:9, a person who does not have the Spirit of Christ does not belong to Him.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Ephesians 1:13, when does the believer receive the Holy Spirit?','options'=>['After years of spiritual maturity','At baptism only','Having believed — simultaneous with faith in Christ','After a second blessing experience'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>"According to 1 Corinthians 6:19, the believer's body is:",'options'=>['A vessel to be discarded at death','The temple of the Holy Spirit','Neutral — neither holy nor sinful','A container for the soul only'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, the Holy Spirit is a force or influence rather than a person.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"According to Ephesians 1:14, the Holy Spirit is described as the __ of the believer's inheritance.",'options'=>['Source','Guarantee (arrabōn — deposit/first instalment)','Completion','Symbol'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Romans 8:11, which power raised Jesus from the dead and dwells in the believer?','options'=>['The power of prayer','The Spirit of Him who raised Jesus from the dead','The power of the church','The power of Scripture alone'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Titus 3:5, salvation is accomplished through the washing of regeneration and renewing of the Holy Spirit.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Romans 8:15-16, the Spirit of adoption enables the believer to cry out:','options'=>["'Lord, be merciful'","'Abba, Father'","'I believe'","'Holy, holy, holy'"],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"According to Galatians 4:6, why did God send the Spirit of His Son into the believer's heart?",'options'=>['To enforce the law','Because they are sons','To prepare them for ministry only','As a reward for obedience'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Romans 8:26-27, the Spirit intercedes for the believer with groanings that cannot be uttered.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"According to Galatians 5:22-23, the fruit of the Spirit is produced by:",'options'=>['Willpower and religious discipline','Spiritual giftedness','The Spirit\'s life operating through the yielded believer','Years of prayer and fasting'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'According to 2 Timothy 1:7, what three qualities describe the spirit God has given the believer?','options'=>['Faith, hope, and love','Fear, power, and obedience','Power, love, and a sound mind','Joy, peace, and patience'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>"According to Ephesians 4:30, the Holy Spirit can be grieved by the believer's conduct.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"According to Acts 1:8, the Holy Spirit's primary purpose in coming upon the believer is to:",'options'=>['Replace the need for Scripture','Give power for witness','Provide material prosperity','Guarantee physical protection'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 1 John 2:20 and 27, the anointing the believer has received from the Holy One:','options'=>['Fades over time if not renewed','Abides in the believer and teaches them concerning all things','Must be re-received at each new level of faith','Is only for those in ministry'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Romans 8:14, being led by the Spirit of God is the mark of those who are children of God.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to 2 Corinthians 3:18, who transforms the believer from glory to glory into the image of Christ?','options'=>["The believer's own effort",'The law','The Spirit of the Lord','Church discipline'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'According to 1 John 4:13, what is described as evidence that the believer abides in Christ and He in them?','options'=>['Performing miracles','Having no sin','The Spirit given to them by God','Attending church faithfully'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to this module, the believer must earn the indwelling of the Holy Spirit through spiritual progress and faithfulness.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"According to Colossians 1:27, what is described as 'the hope of glory'?",'options'=>['The resurrection at the last day','Christ in you','The law perfectly kept','The coming kingdom of God'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Ephesians 3:16, what does the Father give the believer through the Spirit in their inner man?','options'=>['Physical healing','Strength and might','Material blessing','Immunity from suffering'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to John 14:16-17, the Spirit whom Jesus promised to send is described as another Helper — one who would abide with believers forever.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"The Greek word allos used in John 14:16 (another Helper) means:",'options'=>['A different and lesser kind','Another of the same kind — equal to the first','A temporary substitute','A spiritual force only'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"According to 2 Corinthians 1:22, what two things has God done as confirmation of the Spirit's presence?",'options'=>['Anointed and sealed us, and given the Spirit as a guarantee','Healed and blessed us','Called and justified us','Given visions and dreams'],'correct_answer'=>0],
                    ],
                ],
                7 => [
                    'exam_title'      => 'The Reality of Our Authority in Christ — Module Assessment',
                    'time_limit_secs' => 720,
                    'questions'       => [
                        ['type'=>'mcq','question_text'=>'According to Colossians 2:14-15, what did Christ do to principalities and powers at the cross?','options'=>['Made a covenant with them','Disarmed them and made a public spectacle of them, triumphing over them','Assigned them to specific regions','Ignored them completely'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Ephesians 1:20-21, where is Christ seated?','options'=>['In the hearts of believers only','At the right hand of God in the heavenly places, far above all principality and power','On the throne of David in Jerusalem','In the church gathering only'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Ephesians 2:6, the believer is already seated with Christ in the heavenly places — this is a present, not future, reality.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Romans 5:17, those who receive the gift of righteousness will:','options'=>['Wait patiently for authority in the next life','Reign in life through the One, Jesus Christ','Receive special spiritual gifts only','Achieve authority through moral perfection'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to this module, the believer's authority is self-generated through personal holiness and years of spiritual discipline.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"According to Matthew 28:18-19, the word 'therefore' in the Great Commission means:",'options'=>['Despite having no authority, go anyway','Because all authority belongs to Christ, He can delegate it — so go with His authority','Authority must be earned before going','Jesus is giving permission only to the twelve apostles'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'The Greek word exousia (authority) in the New Testament refers to:','options'=>['Physical strength and military power','The right, legal standing, and delegated power to act','An emotional feeling of confidence','Church rank and seniority'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to Acts 19:15, the name of Jesus can be used as a formula by anyone, even those without a genuine relationship with Christ.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Philippians 2:9-11, at the name of Jesus every knee should:','options'=>['Tremble with fear only','Bow — of those in heaven, on earth, and under the earth','Stand in rebellion','Remain neutral until the last day'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to James 4:7, what is the correct sequence for resisting the enemy?','options'=>['Resist the devil first, then submit to God','Submit to God first, then resist the devil and he will flee','Pray loudly, then resist','Ignore the enemy, focus only on worship'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to John 14:13-14, prayer 'in the name of Jesus' means aligning with His will and purpose — it is exercising authority in fellowship with the Father.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Acts 3:6, what did Peter use to command the lame man to walk?','options'=>['Silver and gold','A religious relic','The name of Jesus Christ of Nazareth','Personal righteousness and prayer'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'According to 1 John 4:4, why is the believer able to overcome?','options'=>['Because of their personal strength and discipline','Because He who is in them is greater than he who is in the world','Because they have many years of experience','Because they are morally superior'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Revelation 12:11, the believer overcomes the accuser by the blood of the Lamb and the word of their testimony.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"According to 2 Corinthians 10:5, the believer's authority over the thought life involves:",'options'=>['Ignoring negative thoughts','Casting down arguments and every high thing that exalts itself against the knowledge of God','Replacing all thoughts with positive affirmations only','Seeking counselling for every struggle'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 2 Timothy 1:7, what three qualities characterise the spirit God has given the believer for exercising authority?','options'=>['Wisdom, knowledge, and understanding','Power, love, and a sound mind','Faith, hope, and endurance','Joy, peace, and patience'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to 1 Corinthians 13:1-3, authority and spiritual gifts exercised without love profit nothing.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"According to Matthew 16:19, the language of 'binding and loosing' refers to:",'options'=>['Physical restraint of people','Declaring forbidden or permitted on the basis of heaven\'s authority','Casting spells on enemies','A church disciplinary procedure only'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Hebrews 2:14-15, why did Christ take on flesh and blood?','options'=>['To model a perfect religious life','To destroy the one who had the power of death and release those held in fear of death','To establish the church\'s authority over governments','To introduce the law of Moses to Gentiles'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to this module, the authority of the believer is for personal advantage and self-promotion.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Ephesians 1:22, where are all things placed in relation to Christ?','options'=>['Above His name','Under His feet','Equal to His authority','Beyond His knowledge'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Romans 1:16, the gospel itself is described as:','options'=>['An optional supplement to authority','The power of God to salvation','A cultural tradition','A historical record only'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to John 14:12, Jesus declared that believers who trust in Him will do the works He did, and even greater works.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to 1 Peter 5:8-9, the believer is to resist the enemy by:','options'=>['Running away from all conflict','Being sober and vigilant and resisting him, steadfast in the faith','Asking God to do everything for them','Avoiding all spiritual encounters'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to this module, what is the primary safeguard that must precede all exercise of authority in Christ?','options'=>['Many years of ministry experience','Submission to God','Emotional conviction','A special prophetic calling'],'correct_answer'=>1],
                    ],
                ],
                8 => [
                    'exam_title'      => 'The Reality of Our Fellowship with One Another — Module Assessment',
                    'time_limit_secs' => 720,
                    'questions'       => [
                        ['type'=>'mcq','question_text'=>'According to 1 Corinthians 12:13, by one Spirit all believers were:','options'=>['Organised into separate denominations','Baptized into one body','Given identical spiritual gifts','Assigned individual spiritual journeys'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"A believer can fully express the 'one another' commands of the New Testament without gathering with other believers.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'Hebrews 10:24-25 instructs believers not to forsake:','options'=>['The tithe','The assembling of themselves together','Daily private prayer','Reading the Old Testament'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, the local church is primarily a building where religious services are held.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to this module, fellowship with other believers is:','options'=>['An optional extra for advanced Christians','A new-creation reality that salvation produces','A cultural tradition from the Old Testament','A requirement only for church leaders'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"Ephesians 3:10 teaches that God's wisdom is displayed through:",'options'=>['Individual believers only','Nature and creation','The Church, to principalities and powers in heavenly places','The Old Testament prophets'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to 1 John 1:3-7, fellowship with God and fellowship with other believers are inseparable.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'Acts 2:42 records that the early believers continued steadfastly in all of the following EXCEPT:','options'=>["Apostles' doctrine","Fellowship","Building personal wealth","Breaking of bread and prayers"],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'1 Corinthians 14:26 teaches that when believers gather, each person should:','options'=>['Sit quietly and listen only','Have something to contribute for the edification of all','Follow a fixed liturgy without variation','Limit contributions to professional ministers'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, online teaching can fully replace embodied fellowship, pastoral care, and accountability in a local church.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"According to Galatians 6:1-2, bearing one another's burdens fulfils:",'options'=>['The ten commandments','The law of Moses entirely','The law of Christ','The Levitical priesthood\'s duties'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to this module, forgiveness in fellowship means pretending that nothing wrong happened.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'Ephesians 4:11-16 teaches that the gifts of pastor and teacher are given primarily to:','options'=>['Perform miracles for unbelievers','Equip the saints for the work of ministry and edify the body of Christ','Replace the role of the Holy Spirit','Govern church finances'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Romans 12:10, believers are instructed to give preference to one another in:','options'=>['Arguments and debates','Honour','Financial matters','Leadership positions'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, if a church is doctrinally unsafe or abusive, the believer is required to remain regardless.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'1 Peter 4:10-11 teaches that believers should minister to one another as:','options'=>['Volunteers doing charitable work','Good stewards of the manifold grace of God','Paid church employees','Spiritual authorities over others'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to this module, giving in the body of Christ is best understood as:','options'=>['A tithe required to keep God\'s blessing','A transaction for spiritual services','A family expression of belonging to one another','A financial investment in the church organisation'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to this module, fellowship is first about finding people who are exactly like you.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Hebrews 13:17, why should believers submit to their spiritual leaders?','options'=>['Because leaders are infallible','Because leaders rule with absolute authority','Because they watch out for souls and will give account','Because it is required for salvation'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'According to this module, what is the correct distinction between honour and worship in the context of church leadership?','options'=>['There is no distinction — honour and worship are the same','Honour is value and respect; worship belongs to God alone — leadership is not control','Honour means complete obedience to everything a leader says','Worship is for God; leaders should receive no honour at all'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Acts 2:42-47, the early believers were contributors to community life, not merely consumers.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"According to Colossians 3:12-17, which quality does Paul describe as 'the bond of perfection' — the quality that binds all the others together?",'options'=>['Humility','Forgiveness','Love','Longsuffering'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>"Colossians 3:12 describes the elect of God as 'holy and beloved' — this identity is the basis for the community culture described in that passage.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Philemon 1:6, effective faith-sharing is connected to:','options'=>['Having many years of church experience','Memorising scripture passages','Acknowledging every good thing in us in Christ Jesus','Attending as many church services as possible'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>"According to Acts 2:42, the early believers continued steadfastly in the apostles' doctrine and fellowship. The word 'steadfastly' communicates:",'options'=>['Occasional attendance when convenient','Devoted, persistent commitment — giving oneself to something','Formal church membership only','Cultural tradition without personal conviction'],'correct_answer'=>1],
                    ],
                ],
                9 => [
                    'exam_title'      => 'Devotion — Module Assessment',
                    'time_limit_secs' => 720,
                    'questions'       => [
                        ['type'=>'mcq','question_text'=>'According to this module, New Covenant devotion is best understood as:','options'=>['The mechanism by which believers earn God\'s favour and access','A love-response that enjoys access already established by the blood of Jesus','A religious performance schedule to maintain God\'s presence','An optional practice for spiritually advanced believers'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to Hebrews 10:19-22, devotion creates the believer's access to God in the New Covenant.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Philemon 1:6, faith-sharing becomes effective through:','options'=>['Memorising evangelism scripts','Having many years of church experience','Acknowledging every good thing in us in Christ Jesus','Attending daily prayer meetings'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>'Hebrews 10:19-22 says the believer should come with boldness — the Greek word parresia means:','options'=>['Fearful caution','Free speech, confidence, and openness — the approach of a child to a father','Formal religious protocol','Conditional access based on daily performance'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, devotion to the Word is for formation, not merely information.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'Romans 8:15 says believers have received, not the spirit of bondage to fear, but:','options'=>['The spirit of religious discipline','The Spirit of adoption by whom we cry Abba, Father','The spirit of self-improvement','The Spirit of prophetic gifting'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to this module, the biggest distortion of New Testament devotion is:','options'=>['Praying too briefly','Reading too few chapters of the Bible','Approaching God as a slave driven by fear rather than as a son','Attending church too infrequently'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'2 Timothy 2:15 instructs the believer to study diligently and rightly divide the word of truth.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Colossians 3:16, how should the word of Christ dwell in the believer?','options'=>['Occasionally, when needed for specific problems','Richly — taking up permanent residence, making itself at home','Briefly, as a daily reading obligation','Selectively, focusing only on encouraging verses'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'Romans 12:2 teaches that the believer is transformed by:','options'=>['Increasing social influence','The renewing of the mind','Natural personal development','Attending more church services'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to this module, 'pray without ceasing' in 1 Thessalonians 5:17 means the believer must pray verbally for every waking moment.",'options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Hebrews 4:16, with what posture should believers approach the throne of grace?','options'=>['Timidly, based on their level of personal holiness','Boldly, to obtain mercy and find grace to help in time of need','With long periods of fasting first','With prepared written prayers only'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 2 Corinthians 3:18, beholding the glory of the Lord in the Word produces:','options'=>['Increased biblical knowledge only','Transformation into the same image from glory to glory by the Spirit','A personal sense of unworthiness','Greater obligation to serve the church'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, the goal of prayer in the New Testament is primarily the accumulation of answered requests.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"According to Ephesians 3:16-19, the goal of Paul's prayer for believers is:",'options'=>['That they would become church leaders','That they would be strengthened in the inner man and know the love of Christ experientially','That they would prosper financially','That they would gain supernatural gifts immediately'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to this module, which quality most characterises the spirit that should drive New Testament devotion?','options'=>['The spirit of religious discipline and duty','The spirit of sonship — a beloved child approaching a loving Father','The spirit of striving to become acceptable','The spirit of competition with other believers'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>"According to John 15:7, a believer who abides in Christ and in His word will ask what aligns with God's will and bear much fruit.",'options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"According to 2 Timothy 3:16-17, the goal of Scripture's profitability is that:",'options'=>['The believer would pass theological examinations','The man of God would be complete, thoroughly equipped for every good work','Church leaders would have authority','Believers would have correct answers to all doctrinal debates'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to this module, what does prayer in the New Covenant primarily express?','options'=>['Doubt about whether God is willing to help','Participation in fellowship with a Father who loves His children','Religious obligation to maintain church standing','Competition with other believers\' prayer intensity'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'Galatians 4:6-7 confirms that believers have received the Spirit of adoption and are heirs of God through Christ.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>"According to Acts 2:42, what did the early believers continue steadfastly in that demonstrates Word devotion?",'options'=>['Temple sacrifices and Mosaic ritual',"The apostles' doctrine",'Private silent meditation only','Personal vision and revelation'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Romans 12:1, New Testament worship in relation to devotion means:','options'=>['Attending formal worship services only','Presenting the body as a living sacrifice — a life that is an act of worship','Singing praise songs for a set number of hours','Maintaining a strict prayer journal'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, devotion practised consistently with regularity is more formative than occasional marathon sessions driven by guilt.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Galatians 5:16, what is the fruit of a Spirit-led devotional life?','options'=>['The ability to speak in tongues immediately','Not fulfilling the lust of the flesh','Perfect theological knowledge','Freedom from all trials and difficulties'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'Jude 1:20-21 connects praying in the Holy Spirit to which two outcomes?','options'=>['Instant answers to prayer and financial breakthrough','Building oneself up in faith and keeping oneself in the love of God','Increased church attendance and leadership recognition','Deliverance from all illness and personal problems'],'correct_answer'=>1],
                    ],
                ],
                10 => [
                    'exam_title'      => 'The Baptism of the Holy Spirit — Module Assessment',
                    'time_limit_secs' => 720,
                    'questions'       => [
                        ['type'=>'mcq','question_text'=>'According to 1 Corinthians 12:13, by one Spirit all believers were:','options'=>['Organised into separate prayer groups','Baptized into one body','Given identical ministry roles','Assigned individual spiritual journeys apart from the body'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, the Holy Spirit is given as a reward for holy behaviour and sufficient spiritual performance.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to Galatians 3:2 and 3:14, the Holy Spirit is received by:','options'=>['Works of the law and religious discipline','The hearing of faith — by believing the gospel','Fasting and extended prayer vigils','Moral achievement and church attendance'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Acts 2:32-33, who poured out the Holy Spirit on the Day of Pentecost?','options'=>['The apostles through their prayers','The Father directly from heaven without Christ\'s involvement','The exalted Jesus, having received the promise from the Father','The Holy Spirit acting independently'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to John 7:37-39, the Holy Spirit was given before Jesus was glorified.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>"Ephesians 1:13-14 describes the Holy Spirit as the believer's:",'options'=>['Optional spiritual upgrade','Seal and guarantee of their inheritance until the full redemption','Personal emotional experience','Source of miraculous signs only'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to Romans 8:9, any believer who does not have the Spirit of Christ does not belong to Him.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Acts 1:8, the Holy Spirit empowers believers specifically for:','options'=>['Personal comfort and prosperity','Witness — being His witnesses to the ends of the earth','Religious ceremony and church management','Supernatural signs with no connection to the gospel'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to 1 Corinthians 14:4, what does speaking in tongues produce for the believer personally?','options'=>['Self-glorification and pride','Edification — building up the inner man','Immediate answers to prayer requests','Financial blessing and material provision'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to 1 Corinthians 14:4 and Jude 1:20, speaking in tongues in private prayer edifies the believer.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to 1 Thessalonians 5:19, what does Paul command in relation to the Holy Spirit?','options'=>['Seek the Spirit only in formal church settings','Test every spiritual experience with scepticism','Do not quench the Spirit','Always speak in tongues publicly without order'],'correct_answer'=>2],
                        ['type'=>'mcq','question_text'=>"According to Ephesians 5:18, the command 'be filled with the Spirit' is:",'options'=>['A one-time instruction for new believers only','A continuous present-tense command — keep being filled','An instruction for church leaders only','A metaphor with no literal application'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to 1 Corinthians 14:27-28, public use of tongues in a gathered meeting requires interpretation so all may be edified.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Acts 2:32-33, the pouring out of the Holy Spirit is proof of:','options'=>["The arrival of a new age of miracles separate from Christ's work","The resurrection and exaltation of Jesus Christ","The apostles' personal holiness","The completion of Old Testament prophecy alone"],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>'According to Jude 1:20, believers build themselves up by:','options'=>['Attending more church conferences','Reading motivational books','Praying in the Holy Spirit','Memorising doctrinal statements'],'correct_answer'=>2],
                        ['type'=>'true_false','question_text'=>'According to this module, the baptism of the Holy Spirit is reserved only for spiritually mature or senior believers.','options'=>null,'correct_answer'=>false],
                        ['type'=>'mcq','question_text'=>'According to John 14:16-18, Jesus described the Holy Spirit as:','options'=>['A temporary visitor until Jesus returns','Another Comforter who will abide with believers forever','A spiritual force without personal identity','A reward for those who complete a period of spiritual training'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"According to 2 Corinthians 1:21-22, God has given the Spirit in the believer's heart as:",'options'=>['A temporary presence until full obedience is achieved','The earnest (guarantee/deposit) — the down payment of all that is to come','A sign for unbelievers only','A symbol with no experiential reality'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to this module, spiritual manifestations should never become a basis for pride, superiority, or division among believers.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to Acts 2:1-4, what was the initial sign of the disciples being filled with the Holy Spirit on the Day of Pentecost?','options'=>['They fell into a deep sleep','They were filled and spoke with other tongues as the Spirit gave utterance','They immediately performed miracles of healing','They received written prophetic visions'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"According to this module, what is the consistent goal of the Holy Spirit's work in the believer?",'options'=>['Drawing attention to spiritual gifts and experiences','Christ revealed, believers edified, and the gospel advanced','Personal prosperity and supernatural comfort','Independence from the gathered body of Christ'],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to 1 Corinthians 12:4-7, spiritual gifts are diverse but come from the same Spirit and are given for the profit of all.','options'=>null,'correct_answer'=>true],
                        ['type'=>'mcq','question_text'=>'According to this module, what can cause the believer to quench the Spirit?','options'=>['Being too faithful in attending church','Refusing sound doctrine, living under condemnation, or neglecting prayer and the Word','Having too many spiritual gifts','Praying too frequently in tongues'],'correct_answer'=>1],
                        ['type'=>'mcq','question_text'=>"According to Titus 3:5-6, the Spirit is connected to:",'options'=>["Earning God's approval through righteous works","Regeneration and renewing — poured out abundantly through Jesus Christ","A separate covenant from salvation","Physical health and material prosperity only"],'correct_answer'=>1],
                        ['type'=>'true_false','question_text'=>'According to John 16:13-14, the Spirit guides believers into all truth and consistently glorifies Jesus Christ, not Himself.','options'=>null,'correct_answer'=>true],
                    ],
                ],
            ],
        ];

        foreach ($examData as $courseTitle => $moduleExams) {
            $course = Course::where('title', $courseTitle)->first();
            if (! $course) {
                $this->command->warn("Course not found: {$courseTitle} — skipping");
                continue;
            }

            foreach ($moduleExams as $moduleOrder => $examConfig) {
                $module = Module::where('course_id', $course->id)
                    ->where('order_index', $moduleOrder)
                    ->first();

                if (! $module) {
                    $this->command->warn("Module {$moduleOrder} not found in {$courseTitle} — skipping");
                    continue;
                }

                $exam = Exam::firstOrCreate(
                    ['module_id' => $module->id],
                    [
                        'title'                 => $examConfig['exam_title'],
                        'pass_mark'             => 70,
                        'max_attempts'          => 3,
                        'time_limit_secs'       => $examConfig['time_limit_secs'],
                        'randomize_qs'          => true,
                        'questions_per_session' => 10,
                        'show_answers'          => false,
                        'is_active'             => true,
                    ]
                );

                $count = 0;
                foreach ($examConfig['questions'] as $q) {
                    ExamQuestion::firstOrCreate(
                        ['exam_id' => $exam->id, 'question_text' => $q['question_text']],
                        [
                            'type'           => $q['type'],
                            'options'        => $q['options'],
                            'correct_answer' => $q['correct_answer'],
                            'explanation'    => null,
                            'status'         => 'approved',
                        ]
                    );
                    $count++;
                }

                $this->command->info("  Module {$moduleOrder} ({$module->title}): {$count} questions");
            }

            $this->command->info("✓ {$courseTitle}");
        }
    }
}
